# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jNf7e6e_D4NUGWO1ewy22QUsWF9tvuCT

**Preparação do ambiente**
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile credito.csv
# id_vendedor,valor_emprestimos,quantidade_emprestimos,data
# 104271,448.0,1,20161208
# 21476,826.7,3,20161208
# 87440,313.6,3,20161208
# 15980,-8008.0,6,20161208
# 215906,2212.0,5,20161208
# 33696,2771.3,2,20161208
# 33893,2240.0,3,20161208
# 214946,-4151.0,18,20161208
# 123974,2021.95,2,20161208
# 225870,4039.0,2,20161208

emprestimos = []
with open(file='./credito.csv', mode='r', encoding='utf8') as fp:
  fp.readline() # cabeçalho
  linha = fp.readline()
  while linha:
    linha_emprestimo = {}
    linha_elementos = linha.strip().split(sep=',')
    linha_emprestimo['id_vendedor'] = linha_elementos[0]
    linha_emprestimo['valor_emprestimos'] = linha_elementos[1]
    linha_emprestimo['quantidade_emprestimos'] = linha_elementos[2]
    linha_emprestimo['data'] = linha_elementos[3]
    emprestimos.append(linha_emprestimo)
    linha = fp.readline()

for emprestimo in emprestimos:
  print(emprestimo)

"""# Função map"""

valor_emprestimos_lista = list(map(lambda x: float(x['valor_emprestimos']), emprestimos))

for emprestimo in emprestimos:
    print(emprestimo)

print("Lista de valores de empréstimos:", valor_emprestimos_lista)

"""# Função filter"""

valor_emprestimos_lista_filtrada = list(filter(lambda x: x > 0, valor_emprestimos_lista))

print("Lista de valores de empréstimos filtrados:", valor_emprestimos_lista_filtrada)

"""# Função reduce"""

from functools import reduce

soma_valor_emprestimos = reduce(lambda x, y: x + y, valor_emprestimos_lista_filtrada)

print("Soma dos valores de empréstimos filtrados:", soma_valor_emprestimos)

from functools import reduce

media_valor_emprestimos = soma_valor_emprestimos / len(valor_emprestimos_lista_filtrada)

print("Média dos valores de empréstimos filtrados:", media_valor_emprestimos)